(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"2MDM",
  Authors -> {"Yoxara Villamizar"},
  Emails -> {"yoxarasv@sprace,org.br"},
  Date -> "08.04.2022",
  Version -> "1",
  URLs -> ""};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], Zp -> V[5], ghZp -> U[6], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], h -> S[1], G0 -> S[2], GP -> S[3], Sd -> S[4], phip -> S[5], chi -> F[13]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}};

FR$GoldstoneList={S[2], S[3], S[5]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

V[5] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZp,
    Indices -> {},
    PropagatorLabel -> "Zp" },

U[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZp,
    Indices -> {},
    PropagatorLabel -> "ghZp" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mh,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MSd,
    Indices -> {},
    PropagatorLabel -> "Sd" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZp,
    Indices -> {},
    PropagatorLabel -> "phip" },

F[13] == {
    SelfConjugate -> True,
    PropagatorType -> Straight,
    PropagatorArrow -> None*PDG -> {9910012},
    Mass -> Mchi,
    Indices -> {},
    PropagatorLabel -> "chi" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ U[6] ] = GaugeXi[U[5]];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ F[13] ] = GaugeXi[F[7]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MZp[ ___ ] := MZp;
MTA[ ___ ] := MTA;
MT[ ___ ] := MT;
MB[ ___ ] := MB;
Mh[ ___ ] := Mh;
MSd[ ___ ] := MSd;
Mchi[ ___ ] := Mchi;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam1, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam1, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam1, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*(2*cosa^2*lam1 + lam3*sina^2), 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-I)*(2*cosa^2*lam1 + lam3*sina^2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*(cosa^4*lam1 + cosa^2*lam3*sina^2 + lam2*sina^4), 0}},

C[ S[2] , S[2] , S[5] , S[5] ] == {{(-I)*lam3, 0}},

C[ S[3] , -S[3] , S[5] , S[5] ] == {{(-I)*lam3, 0}},

C[ S[1] , S[1] , S[5] , S[5] ] == {{(-I)*(cosa^2*lam3 + 2*lam2*sina^2), 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-6*I)*lam2, 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(cosa^2*lam3 + 2*lam1*sina^2), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*(cosa^2*lam3 + 2*lam1*sina^2), 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(cosa^4*lam3 + 2*cosa^2*(3*lam1 + 3*lam2 - 2*lam3)*sina^2 + lam3*sina^4), 0}},

C[ S[5] , S[5] , S[4] , S[4] ] == {{(-I)*(2*cosa^2*lam2 + lam3*sina^2), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*(cosa^4*lam2 + cosa^2*lam3*sina^2 + lam1*sina^4), 0}},

C[ S[2] , S[2] , S[1] , S[4] ] == {{(-I)*cosa*(2*lam1 - lam3)*sina, 0}},

C[ S[3] , -S[3] , S[1] , S[4] ] == {{(-I)*cosa*(2*lam1 - lam3)*sina, 0}},

C[ S[1] , S[1] , S[1] , S[4] ] == {{(-3*I)*cosa*sina*(cosa^2*(2*lam1 - lam3) + (-2*lam2 + lam3)*sina^2), 0}},

C[ S[1] , S[5] , S[5] , S[4] ] == {{I*cosa*(2*lam2 - lam3)*sina, 0}},

C[ S[1] , S[4] , S[4] , S[4] ] == {{(3*I)*cosa*sina*(cosa^2*(2*lam2 - lam3) + (-2*lam1 + lam3)*sina^2), 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*cosa*lam1*vev + I*lam3*sina*vev2, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*cosa*lam1*vev + I*lam3*sina*vev2, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*(2*cosa^3*lam1*vev + cosa*lam3*sina^2*vev - cosa^2*lam3*sina*vev2 - 2*lam2*sina^3*vev2), 0}},

C[ S[1] , S[5] , S[5] ] == {{(-I)*(cosa*lam3*vev - 2*lam2*sina*vev2), 0}},

C[ S[1] , S[4] , S[4] ] == {{(-I)*(cosa^3*lam3*vev + 2*cosa*(3*lam1 - lam3)*sina^2*vev + 2*cosa^2*(-3*lam2 + lam3)*sina*vev2 - lam3*sina^3*vev2), 0}},

C[ S[2] , S[2] , S[4] ] == {{(-I)*(2*lam1*sina*vev + cosa*lam3*vev2), 0}},

C[ S[3] , -S[3] , S[4] ] == {{(-I)*(2*lam1*sina*vev + cosa*lam3*vev2), 0}},

C[ S[1] , S[1] , S[4] ] == {{(-I)*(2*cosa^2*(3*lam1 - lam3)*sina*vev + lam3*sina^3*vev + cosa^3*lam3*vev2 + 2*cosa*(3*lam2 - lam3)*sina^2*vev2), 0}},

C[ S[5] , S[5] , S[4] ] == {{(-I)*(lam3*sina*vev + 2*cosa*lam2*vev2), 0}},

C[ S[4] , S[4] , S[4] ] == {{(-3*I)*(cosa^2*lam3*sina*vev + 2*lam1*sina^3*vev + 2*cosa^3*lam2*vev2 + cosa*lam3*sina^2*vev2), 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc32, 0}, {I*gc32, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc35, 0}, {I*gc35, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc37, 0}, {I*gc37, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*cosa*EL^2*vev)/sw^2, 0}},

C[ S[4] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*sina*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc41, 0}, {I*gc41, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc42, 0}, {I*gc42, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc44, 0}, {I*gc44, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc46, 0}, {I*gc46, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*cosa*EL^2*vev)/sw^2, 0}},

C[ S[4] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*sina*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc50, 0}, {I*gc50, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc51, 0}, {I*gc51, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(EL^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc53, 0}, {I*gc53, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc55, 0}, {I*gc55, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(EL^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc57, 0}, {I*gc57, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*cosa*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[4] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*sina*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc60*SUNF[e3x2, e1x1, e2x1], (GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/(2*aS)}, {gc60*SUNF[e3x2, e1x1, e2x1], (GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/(2*aS)}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc61*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {gc61*SUNF[e1x2, e2x2, e3x2], -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}, {gc61*SUNF[e1x2, e2x2, e3x2], -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}, {-(gc61*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {-(gc61*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {gc61*SUNF[e1x2, e2x2, e3x2], -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc62*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}, {I*gc62*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc62*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}},

C[ F[13] , F[13] , S[5] ] == {{gc63L, 0}, {gc63R, 0}},

C[ F[13] , F[13] , S[4] ] == {{I*gc64, 0}, {I*gc64, 0}},

C[ F[13] , F[13] , S[1] ] == {{I*gc65, 0}, {I*gc65, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc66L*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MB)}, {gc66R*IndexDelta[e1x2, e2x2], -1/2*(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MT}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc67L*IndexDelta[e1x2, e2x2], -1/2*(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {gc67R*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MB)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc68*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc68*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] ] == {{I*gc69*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc69*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[6] , F[3] , -S[3] ] == {{gc71, 0}, {0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc72L, 0}, {gc72R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc73, 0}, {I*gc73, 0}},

C[ -F[6] , F[6] , S[4] ] == {{I*gc74, 0}, {I*gc74, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc75L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MT)}, {gc75R*IndexDelta[e1x2, e2x2], -1/2*(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MB}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc76L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MT)}, {gc76R*IndexDelta[e1x2, e2x2], -1/2*(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc77*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc77*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{I*gc78*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc78*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*(cosa*EL^2)/sw, 0}},

C[ -S[3] , S[4] , V[1] , V[3] ] == {{-1/2*(EL^2*sina)/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc84, 0}, {I*gc84, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc85, 0}, {gc85, 0}},

C[ -S[3] , S[4] , V[3] ] == {{-gc86, 0}, {gc86, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc87, 0}, {I*gc87, 0}, {I*gc87, 0}, {(-I)*gc87, 0}, {(-I)*gc87, 0}, {I*gc87, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{(cosa*EL^2)/(2*sw), 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(EL^2*sina)/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc92, 0}, {I*gc92, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc93, 0}, {gc93, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc94, 0}, {gc94, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*cosa^2*EL^2)/sw^2, 0}},

C[ S[1] , S[4] , V[3] , -V[3] ] == {{((I/2)*cosa*EL^2*sina)/sw^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*sina^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*cosa*EL^2*vev)/sw^2, 0}},

C[ S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*sina*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc102, 0}, {(-I)*gc102, 0}, {(2*I)*gc102, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc103, 0}, {I*gc103, 0}, {I*gc103, 0}, {(-I)*gc103, 0}, {(-I)*gc103, 0}, {I*gc103, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc104, 0}, {(-I)*gc104, 0}, {(2*I)*gc104, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc105R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc107, 0}, {gc107, 0}},

C[ S[2] , S[4] , V[2] ] == {{-gc108, 0}, {gc108, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc109, 0}, {I*gc109, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{(cosa*EL^2)/(2*cw), 0}},

C[ -S[3] , S[4] , V[3] , V[2] ] == {{(EL^2*sina)/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*(cosa*EL^2)/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-1/2*(EL^2*sina)/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-1/2*(EL^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc118, 0}, {I*gc118, 0}, {I*gc118, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*cosa^2*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[4] , V[2] , V[2] ] == {{((I/2)*cosa*EL^2*sina*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*sina^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*cosa*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*sina*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc126, 0}, {(-I)*gc126, 0}, {(2*I)*gc126, 0}},

C[ S[1] , S[5] , V[5] ] == {{-gc127, 0}, {gc127, 0}},

C[ S[5] , S[4] , V[5] ] == {{-gc128, 0}, {gc128, 0}},

C[ S[5] , S[5] , V[5] , V[5] ] == {{(2*I)*gZp^2*QBphi^2, 0}},

C[ S[4] , S[4] , V[5] , V[5] ] == {{(2*I)*cosa^2*gZp^2*QBphi^2, 0}},

C[ S[1] , S[4] , V[5] , V[5] ] == {{(-2*I)*cosa*gZp^2*QBphi^2*sina, 0}},

C[ S[1] , S[1] , V[5] , V[5] ] == {{(2*I)*gZp^2*QBphi^2*sina^2, 0}},

C[ S[4] , V[5] , V[5] ] == {{(2*I)*cosa*gZp^2*QBphi^2*vev2, 0}},

C[ S[1] , V[5] , V[5] ] == {{(-2*I)*gZp^2*QBphi^2*sina*vev2, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc135, 0}, {I*gc135, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc136, 0}, {I*gc136, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc137, 0}, {I*gc137, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc138*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc138*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc139*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc139*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc140*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc140*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc141*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc141*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc142*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc142*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc143*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc143*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc148*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc148*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc149*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc149*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc150*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc150*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc151*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc151*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc152*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc152*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc153*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc153*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc154*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc155*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc156*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc157*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc158*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc159*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc160, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc161, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc162, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc163, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc164, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc165, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc166L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc166R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc167L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc167R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc168L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc168R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc169L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc169R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc170L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc170R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc171L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc171R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc172, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc173, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc174, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc175L, 0}, {I*gc175R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc176L, 0}, {I*gc176R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc177L, 0}, {I*gc177R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[5] ] == {{I*gc178*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc178*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[5] ] == {{I*gc179*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc179*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[5] ] == {{I*gc180*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc180*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[5] ] == {{I*gc181*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc181*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[5] ] == {{I*gc182*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc182*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[5] ] == {{I*gc183*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc183*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ F[13] , F[13] , V[5] ] == {{I*gc184L, 0}, {I*gc184R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc32 -> -EL,
     gc34 -> EL,
     gc35 -> -EL,
     gc37 -> EL,
     gc41 -> -EL,
     gc42 -> -((cw*EL)/sw),
     gc44 -> (cw*EL)/sw,
     gc46 -> -EL,
     gc50 -> EL,
     gc51 -> (cw*EL)/sw,
     gc53 -> -((cw*EL)/sw),
     gc55 -> (cw*EL)/sw,
     gc57 -> -((cw*EL)/sw),
     gc60 -> GS,
     gc61 -> -GS,
     gc62 -> -GS^2,
     gc63L -> ychi/Sqrt[2],
     gc63R -> -(ychi/Sqrt[2]),
     gc64 -> -((cosa*ychi)/Sqrt[2]),
     gc65 -> (sina*ychi)/Sqrt[2],
     gc66L -> yb,
     gc66R -> -yt,
     gc67L -> -(yb/Sqrt[2]),
     gc67R -> yb/Sqrt[2],
     gc68 -> -((cosa*yb)/Sqrt[2]),
     gc69 -> -((sina*yb)/Sqrt[2]),
     gc71 -> ytau,
     gc72L -> -(ytau/Sqrt[2]),
     gc72R -> ytau/Sqrt[2],
     gc73 -> -((cosa*ytau)/Sqrt[2]),
     gc74 -> -((sina*ytau)/Sqrt[2]),
     gc75L -> yt,
     gc75R -> -yb,
     gc76L -> yt/Sqrt[2],
     gc76R -> -(yt/Sqrt[2]),
     gc77 -> -((cosa*yt)/Sqrt[2]),
     gc78 -> -((sina*yt)/Sqrt[2]),
     gc84 -> EL/(2*sw),
     gc85 -> -1/2*(cosa*EL)/sw,
     gc86 -> -1/2*(EL*sina)/sw,
     gc87 -> EL,
     gc92 -> -1/2*EL/sw,
     gc93 -> -1/2*(cosa*EL)/sw,
     gc94 -> -1/2*(EL*sina)/sw,
     gc102 -> -EL^2,
     gc103 -> (cw*EL)/sw,
     gc104 -> EL^2/sw^2,
     gc105R -> -ytau,
     gc107 -> -1/2*(cosa*EL*(cw^2 + sw^2))/(cw*sw),
     gc108 -> -1/2*(EL*sina*(cw^2 + sw^2))/(cw*sw),
     gc109 -> -1/2*(cw*EL)/sw + (EL*sw)/(2*cw),
     gc118 -> (cw*EL^2)/sw,
     gc126 -> -((cw^2*EL^2)/sw^2),
     gc127 -> gZp*QBphi*sina,
     gc128 -> cosa*gZp*QBphi,
     gc135 -> -EL,
     gc136 -> -EL,
     gc137 -> -EL,
     gc138 -> (2*EL)/3,
     gc139 -> (2*EL)/3,
     gc140 -> (2*EL)/3,
     gc141 -> -1/3*EL,
     gc142 -> -1/3*EL,
     gc143 -> -1/3*EL,
     gc148 -> GS,
     gc149 -> GS,
     gc150 -> GS,
     gc151 -> GS,
     gc152 -> GS,
     gc153 -> GS,
     gc154 -> EL/(Sqrt[2]*sw),
     gc155 -> EL/(Sqrt[2]*sw),
     gc156 -> EL/(Sqrt[2]*sw),
     gc157 -> EL/(Sqrt[2]*sw),
     gc158 -> EL/(Sqrt[2]*sw),
     gc159 -> EL/(Sqrt[2]*sw),
     gc160 -> EL/(Sqrt[2]*sw),
     gc161 -> EL/(Sqrt[2]*sw),
     gc162 -> EL/(Sqrt[2]*sw),
     gc163 -> EL/(Sqrt[2]*sw),
     gc164 -> EL/(Sqrt[2]*sw),
     gc165 -> EL/(Sqrt[2]*sw),
     gc166L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc166R -> (-2*EL*sw)/(3*cw),
     gc167L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc167R -> (-2*EL*sw)/(3*cw),
     gc168L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc168R -> (-2*EL*sw)/(3*cw),
     gc169L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc169R -> (EL*sw)/(3*cw),
     gc170L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc170R -> (EL*sw)/(3*cw),
     gc171L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc171R -> (EL*sw)/(3*cw),
     gc172 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc173 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc174 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc175L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc175R -> (EL*sw)/cw,
     gc176L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc176R -> (EL*sw)/cw,
     gc177L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc177R -> (EL*sw)/cw,
     gc178 -> gZp*QBq,
     gc179 -> gZp*QBq,
     gc180 -> gZp*QBq,
     gc181 -> gZp*QBq,
     gc182 -> gZp*QBq,
     gc183 -> gZp*QBq,
     gc184L -> gchi,
     gc184R -> -gchi};

