(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"2MDM",
  Authors -> {"Yoxara Villamizar"},
  Emails -> {"yoxarasv@sprace,org.br"},
  Date -> "08.04.2022",
  Version -> "1",
  URLs -> ""};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], Zp -> V[5], ghZp -> U[6], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], h -> S[1], G0 -> S[2], GP -> S[3], Sd -> S[4], phip -> S[5], chi -> F[13]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}};

FR$GoldstoneList={S[2], S[3], S[5]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

V[5] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZp,
    Indices -> {},
    PropagatorLabel -> "Zp" },

U[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZp,
    Indices -> {},
    PropagatorLabel -> "ghZp" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mh,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MSd,
    Indices -> {},
    PropagatorLabel -> "Sd" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZp,
    Indices -> {},
    PropagatorLabel -> "phip" },

F[13] == {
    SelfConjugate -> True,
    PropagatorType -> Straight,
    PropagatorArrow -> None*PDG -> {9910012},
    Mass -> Mchi,
    Indices -> {},
    PropagatorLabel -> "chi" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ U[6] ] = GaugeXi[U[5]];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ F[13] ] = GaugeXi[F[7]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MZp[ ___ ] := MZp;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
Mh[ ___ ] := Mh;
MSd[ ___ ] := MSd;
Mchi[ ___ ] := Mchi;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam1, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam1, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam1, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*(2*cosa^2*lam1 + lam3*sina^2), 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-I)*(2*cosa^2*lam1 + lam3*sina^2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*(cosa^4*lam1 + cosa^2*lam3*sina^2 + lam2*sina^4), 0}},

C[ S[2] , S[2] , S[5] , S[5] ] == {{(-I)*lam3, 0}},

C[ S[3] , -S[3] , S[5] , S[5] ] == {{(-I)*lam3, 0}},

C[ S[1] , S[1] , S[5] , S[5] ] == {{(-I)*(cosa^2*lam3 + 2*lam2*sina^2), 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-6*I)*lam2, 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(cosa^2*lam3 + 2*lam1*sina^2), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*(cosa^2*lam3 + 2*lam1*sina^2), 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(cosa^4*lam3 + 2*cosa^2*(3*lam1 + 3*lam2 - 2*lam3)*sina^2 + lam3*sina^4), 0}},

C[ S[5] , S[5] , S[4] , S[4] ] == {{(-I)*(2*cosa^2*lam2 + lam3*sina^2), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*(cosa^4*lam2 + cosa^2*lam3*sina^2 + lam1*sina^4), 0}},

C[ S[2] , S[2] , S[1] , S[4] ] == {{(-I)*cosa*(2*lam1 - lam3)*sina, 0}},

C[ S[3] , -S[3] , S[1] , S[4] ] == {{(-I)*cosa*(2*lam1 - lam3)*sina, 0}},

C[ S[1] , S[1] , S[1] , S[4] ] == {{(-3*I)*cosa*sina*(cosa^2*(2*lam1 - lam3) + (-2*lam2 + lam3)*sina^2), 0}},

C[ S[1] , S[5] , S[5] , S[4] ] == {{I*cosa*(2*lam2 - lam3)*sina, 0}},

C[ S[1] , S[4] , S[4] , S[4] ] == {{(3*I)*cosa*sina*(cosa^2*(2*lam2 - lam3) + (-2*lam1 + lam3)*sina^2), 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*cosa*lam1*vev + I*lam3*sina*vev2, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*cosa*lam1*vev + I*lam3*sina*vev2, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*(2*cosa^3*lam1*vev + cosa*lam3*sina^2*vev - cosa^2*lam3*sina*vev2 - 2*lam2*sina^3*vev2), 0}},

C[ S[1] , S[5] , S[5] ] == {{(-I)*(cosa*lam3*vev - 2*lam2*sina*vev2), 0}},

C[ S[1] , S[4] , S[4] ] == {{(-I)*(cosa^3*lam3*vev + 2*cosa*(3*lam1 - lam3)*sina^2*vev + 2*cosa^2*(-3*lam2 + lam3)*sina*vev2 - lam3*sina^3*vev2), 0}},

C[ S[2] , S[2] , S[4] ] == {{(-I)*(2*lam1*sina*vev + cosa*lam3*vev2), 0}},

C[ S[3] , -S[3] , S[4] ] == {{(-I)*(2*lam1*sina*vev + cosa*lam3*vev2), 0}},

C[ S[1] , S[1] , S[4] ] == {{(-I)*(2*cosa^2*(3*lam1 - lam3)*sina*vev + lam3*sina^3*vev + cosa^3*lam3*vev2 + 2*cosa*(3*lam2 - lam3)*sina^2*vev2), 0}},

C[ S[5] , S[5] , S[4] ] == {{(-I)*(lam3*sina*vev + 2*cosa*lam2*vev2), 0}},

C[ S[4] , S[4] , S[4] ] == {{(-3*I)*(cosa^2*lam3*sina*vev + 2*lam1*sina^3*vev + 2*cosa^3*lam2*vev2 + cosa*lam3*sina^2*vev2), 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc32, 0}, {I*gc32, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc35, 0}, {I*gc35, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc37, 0}, {I*gc37, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*cosa*EL^2*vev)/sw^2, 0}},

C[ S[4] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*sina*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc41, 0}, {I*gc41, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc42, 0}, {I*gc42, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc44, 0}, {I*gc44, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc46, 0}, {I*gc46, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*cosa*EL^2*vev)/sw^2, 0}},

C[ S[4] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*sina*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc50, 0}, {I*gc50, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc51, 0}, {I*gc51, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(EL^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc53, 0}, {I*gc53, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc55, 0}, {I*gc55, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(EL^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc57, 0}, {I*gc57, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*cosa*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[4] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*sina*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc60*SUNF[e3x2, e1x1, e2x1], (GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/(2*aS)}, {gc60*SUNF[e3x2, e1x1, e2x1], (GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/(2*aS)}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc61*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {gc61*SUNF[e1x2, e2x2, e3x2], -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}, {gc61*SUNF[e1x2, e2x2, e3x2], -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}, {-(gc61*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {-(gc61*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {gc61*SUNF[e1x2, e2x2, e3x2], -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc62*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}, {I*gc62*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc62*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}},

C[ F[13] , F[13] , S[5] ] == {{gc63L, 0}, {gc63R, 0}},

C[ F[13] , F[13] , S[4] ] == {{I*gc64, 0}, {I*gc64, 0}},

C[ F[13] , F[13] , S[1] ] == {{I*gc65, 0}, {I*gc65, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc66L*IndexDelta[e1x2, e2x2], (yb*Conjugate[CKM3x3]*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MB)}, {gc66R*IndexDelta[e1x2, e2x2], -1/2*(yt*Conjugate[CKM3x3]*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MT}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc67L*IndexDelta[e1x2, e2x2], (ydo*Conjugate[CKM2x1]*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{c, c}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MD)}, {gc67R*IndexDelta[e1x2, e2x2], -1/2*(yc*Conjugate[CKM2x1]*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MC}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc68L*IndexDelta[e1x2, e2x2], (ydo*Conjugate[CKM1x1]*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "R"] + MD*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MD)}, {gc68R*IndexDelta[e1x2, e2x2], -1/2*(yup*Conjugate[CKM1x1]*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{d, d}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MU}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc69L*IndexDelta[e1x2, e2x2], (ys*Conjugate[CKM2x2]*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{c, c}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MS)}, {gc69R*IndexDelta[e1x2, e2x2], -1/2*(yc*Conjugate[CKM2x2]*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MC}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc70L*IndexDelta[e1x2, e2x2], (ys*Conjugate[CKM1x2]*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "R"] + MS*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MS)}, {gc70R*IndexDelta[e1x2, e2x2], -1/2*(yup*Conjugate[CKM1x2]*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{s, s}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MU}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc71L*IndexDelta[e1x2, e2x2], -1/2*(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {gc71R*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MB)}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc72L*IndexDelta[e1x2, e2x2], -1/2*(ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}, {gc72R*IndexDelta[e1x2, e2x2], (ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MD)}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc73L*IndexDelta[e1x2, e2x2], -1/2*(ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}, {gc73R*IndexDelta[e1x2, e2x2], (ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MS)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc74*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc74*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc75*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}, {I*gc75*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc76*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}, {I*gc76*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] ] == {{I*gc77*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc77*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[4] ] == {{I*gc78*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}, {I*gc78*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[4] ] == {{I*gc79*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}, {I*gc79*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[4] , F[1] , -S[3] ] == {{gc83, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc84, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc85, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc86L, 0}, {gc86R, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc87L, 0}, {gc87R, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc88L, 0}, {gc88R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc89, 0}, {I*gc89, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc90, 0}, {I*gc90, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc91, 0}, {I*gc91, 0}},

C[ -F[4] , F[4] , S[4] ] == {{I*gc92, 0}, {I*gc92, 0}},

C[ -F[5] , F[5] , S[4] ] == {{I*gc93, 0}, {I*gc93, 0}},

C[ -F[6] , F[6] , S[4] ] == {{I*gc94, 0}, {I*gc94, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc95L*IndexDelta[e1x2, e2x2], (CKM2x1*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MC)}, {gc95R*IndexDelta[e1x2, e2x2], -1/2*(CKM2x1*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{c, c}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MD}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc96L*IndexDelta[e1x2, e2x2], (CKM2x2*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MC)}, {gc96R*IndexDelta[e1x2, e2x2], -1/2*(CKM2x2*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{c, c}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MS}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc97L*IndexDelta[e1x2, e2x2], (CKM3x3*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MT)}, {gc97R*IndexDelta[e1x2, e2x2], -1/2*(CKM3x3*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MB}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc98L*IndexDelta[e1x2, e2x2], (CKM1x1*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{d, d}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MU)}, {gc98R*IndexDelta[e1x2, e2x2], -1/2*(CKM1x1*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "R"] + MD*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MD}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc99L*IndexDelta[e1x2, e2x2], (CKM1x2*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{s, s}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MU)}, {gc99R*IndexDelta[e1x2, e2x2], -1/2*(CKM1x2*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "R"] + MS*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MS}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc100L*IndexDelta[e1x2, e2x2], (yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MC)}, {gc100R*IndexDelta[e1x2, e2x2], -1/2*(yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc101L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MT)}, {gc101R*IndexDelta[e1x2, e2x2], -1/2*(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc102L*IndexDelta[e1x2, e2x2], (yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MU)}, {gc102R*IndexDelta[e1x2, e2x2], -1/2*(yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc103*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}, {I*gc103*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc104*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc104*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc105*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}, {I*gc105*IndexDelta[e1x2, e2x2], ((-1/2*I)*cosa*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[4] ] == {{I*gc106*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}, {I*gc106*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{I*gc107*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc107*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[4] ] == {{I*gc108*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}, {I*gc108*IndexDelta[e1x2, e2x2], ((-1/2*I)*sina*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] ] == {{0, (-1/2*I)*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}, {0, I*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*(cosa*EL^2)/sw, 0}},

C[ -S[3] , S[4] , V[1] , V[3] ] == {{-1/2*(EL^2*sina)/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc116, 0}, {I*gc116, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc117, 0}, {gc117, 0}},

C[ -S[3] , S[4] , V[3] ] == {{-gc118, 0}, {gc118, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc119, 0}, {I*gc119, 0}, {I*gc119, 0}, {(-I)*gc119, 0}, {(-I)*gc119, 0}, {I*gc119, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{(cosa*EL^2)/(2*sw), 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(EL^2*sina)/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc124, 0}, {I*gc124, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc125, 0}, {gc125, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc126, 0}, {gc126, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*cosa^2*EL^2)/sw^2, 0}},

C[ S[1] , S[4] , V[3] , -V[3] ] == {{((I/2)*cosa*EL^2*sina)/sw^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*sina^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*cosa*EL^2*vev)/sw^2, 0}},

C[ S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*sina*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc134, 0}, {(-I)*gc134, 0}, {(2*I)*gc134, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc135, 0}, {I*gc135, 0}, {I*gc135, 0}, {(-I)*gc135, 0}, {(-I)*gc135, 0}, {I*gc135, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc136, 0}, {(-I)*gc136, 0}, {(2*I)*gc136, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc137R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc138R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc139R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc141, 0}, {gc141, 0}},

C[ S[2] , S[4] , V[2] ] == {{-gc142, 0}, {gc142, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc143, 0}, {I*gc143, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{(cosa*EL^2)/(2*cw), 0}},

C[ -S[3] , S[4] , V[3] , V[2] ] == {{(EL^2*sina)/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*(cosa*EL^2)/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-1/2*(EL^2*sina)/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-1/2*(EL^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc152, 0}, {I*gc152, 0}, {I*gc152, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*cosa^2*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[4] , V[2] , V[2] ] == {{((I/2)*cosa*EL^2*sina*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*sina^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*cosa*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*sina*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc160, 0}, {(-I)*gc160, 0}, {(2*I)*gc160, 0}},

C[ S[1] , S[5] , V[5] ] == {{-gc161, 0}, {gc161, 0}},

C[ S[5] , S[4] , V[5] ] == {{-gc162, 0}, {gc162, 0}},

C[ S[5] , S[5] , V[5] , V[5] ] == {{(2*I)*gZp^2*QBphi^2, 0}},

C[ S[4] , S[4] , V[5] , V[5] ] == {{(2*I)*cosa^2*gZp^2*QBphi^2, 0}},

C[ S[1] , S[4] , V[5] , V[5] ] == {{(-2*I)*cosa*gZp^2*QBphi^2*sina, 0}},

C[ S[1] , S[1] , V[5] , V[5] ] == {{(2*I)*gZp^2*QBphi^2*sina^2, 0}},

C[ S[4] , V[5] , V[5] ] == {{(2*I)*cosa*gZp^2*QBphi^2*vev2, 0}},

C[ S[1] , V[5] , V[5] ] == {{(-2*I)*gZp^2*QBphi^2*sina*vev2, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc169, 0}, {I*gc169, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc170, 0}, {I*gc170, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc171, 0}, {I*gc171, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc172*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc172*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc173*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc173*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc174*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc174*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc175*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc175*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc176*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc176*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc177*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc177*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc178*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc178*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc179*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc179*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc180*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc180*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc181*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc181*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc182*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc182*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc183*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc183*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc184*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x1*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc185*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x2*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc186*IndexDelta[e1x2, e2x2], ((I/2)*CKM3x3*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc187*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x1*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc188*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x2*EL*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc189*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM3x3]*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc190*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x1]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc191*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x1]*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc192*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x2]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc193*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x2]*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc194, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc195, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc196, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc197, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc198, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc199, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc200L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc200R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc201L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc201R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc202L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc202R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc203L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc203R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc204L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc204R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc205L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc205R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc206, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc207, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc208, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc209L, 0}, {I*gc209R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc210L, 0}, {I*gc210R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc211L, 0}, {I*gc211R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[5] ] == {{I*gc212*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc212*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[5] ] == {{I*gc213*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc213*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[5] ] == {{I*gc214*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc214*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[5] ] == {{I*gc215*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc215*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[5] ] == {{I*gc216*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc216*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[5] ] == {{I*gc217*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc217*IndexDelta[e1x2, e2x2], I*gZp*QBq*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ F[13] , F[13] , V[5] ] == {{I*gc218L, 0}, {I*gc218R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc32 -> -EL,
     gc34 -> EL,
     gc35 -> -EL,
     gc37 -> EL,
     gc41 -> -EL,
     gc42 -> -((cw*EL)/sw),
     gc44 -> (cw*EL)/sw,
     gc46 -> -EL,
     gc50 -> EL,
     gc51 -> (cw*EL)/sw,
     gc53 -> -((cw*EL)/sw),
     gc55 -> (cw*EL)/sw,
     gc57 -> -((cw*EL)/sw),
     gc60 -> GS,
     gc61 -> -GS,
     gc62 -> -GS^2,
     gc63L -> ychi/Sqrt[2],
     gc63R -> -(ychi/Sqrt[2]),
     gc64 -> -((cosa*ychi)/Sqrt[2]),
     gc65 -> (sina*ychi)/Sqrt[2],
     gc66L -> yb*Conjugate[CKM3x3],
     gc66R -> -(yt*Conjugate[CKM3x3]),
     gc67L -> ydo*Conjugate[CKM2x1],
     gc67R -> -(yc*Conjugate[CKM2x1]),
     gc68L -> ydo*Conjugate[CKM1x1],
     gc68R -> -(yup*Conjugate[CKM1x1]),
     gc69L -> ys*Conjugate[CKM2x2],
     gc69R -> -(yc*Conjugate[CKM2x2]),
     gc70L -> ys*Conjugate[CKM1x2],
     gc70R -> -(yup*Conjugate[CKM1x2]),
     gc71L -> -(yb/Sqrt[2]),
     gc71R -> yb/Sqrt[2],
     gc72L -> -(ydo/Sqrt[2]),
     gc72R -> ydo/Sqrt[2],
     gc73L -> -(ys/Sqrt[2]),
     gc73R -> ys/Sqrt[2],
     gc74 -> -((cosa*yb)/Sqrt[2]),
     gc75 -> -((cosa*ydo)/Sqrt[2]),
     gc76 -> -((cosa*ys)/Sqrt[2]),
     gc77 -> -((sina*yb)/Sqrt[2]),
     gc78 -> -((sina*ydo)/Sqrt[2]),
     gc79 -> -((sina*ys)/Sqrt[2]),
     gc83 -> ye,
     gc84 -> ym,
     gc85 -> ytau,
     gc86L -> -(ye/Sqrt[2]),
     gc86R -> ye/Sqrt[2],
     gc87L -> -(ym/Sqrt[2]),
     gc87R -> ym/Sqrt[2],
     gc88L -> -(ytau/Sqrt[2]),
     gc88R -> ytau/Sqrt[2],
     gc89 -> -((cosa*ye)/Sqrt[2]),
     gc90 -> -((cosa*ym)/Sqrt[2]),
     gc91 -> -((cosa*ytau)/Sqrt[2]),
     gc92 -> -((sina*ye)/Sqrt[2]),
     gc93 -> -((sina*ym)/Sqrt[2]),
     gc94 -> -((sina*ytau)/Sqrt[2]),
     gc95L -> CKM2x1*yc,
     gc95R -> -(CKM2x1*ydo),
     gc96L -> CKM2x2*yc,
     gc96R -> -(CKM2x2*ys),
     gc97L -> CKM3x3*yt,
     gc97R -> -(CKM3x3*yb),
     gc98L -> CKM1x1*yup,
     gc98R -> -(CKM1x1*ydo),
     gc99L -> CKM1x2*yup,
     gc99R -> -(CKM1x2*ys),
     gc100L -> yc/Sqrt[2],
     gc100R -> -(yc/Sqrt[2]),
     gc101L -> yt/Sqrt[2],
     gc101R -> -(yt/Sqrt[2]),
     gc102L -> yup/Sqrt[2],
     gc102R -> -(yup/Sqrt[2]),
     gc103 -> -((cosa*yc)/Sqrt[2]),
     gc104 -> -((cosa*yt)/Sqrt[2]),
     gc105 -> -((cosa*yup)/Sqrt[2]),
     gc106 -> -((sina*yc)/Sqrt[2]),
     gc107 -> -((sina*yt)/Sqrt[2]),
     gc108 -> -((sina*yup)/Sqrt[2]),
     gc116 -> EL/(2*sw),
     gc117 -> -1/2*(cosa*EL)/sw,
     gc118 -> -1/2*(EL*sina)/sw,
     gc119 -> EL,
     gc124 -> -1/2*EL/sw,
     gc125 -> -1/2*(cosa*EL)/sw,
     gc126 -> -1/2*(EL*sina)/sw,
     gc134 -> -EL^2,
     gc135 -> (cw*EL)/sw,
     gc136 -> EL^2/sw^2,
     gc137R -> -ye,
     gc138R -> -ym,
     gc139R -> -ytau,
     gc141 -> -1/2*(cosa*EL*(cw^2 + sw^2))/(cw*sw),
     gc142 -> -1/2*(EL*sina*(cw^2 + sw^2))/(cw*sw),
     gc143 -> -1/2*(cw*EL)/sw + (EL*sw)/(2*cw),
     gc152 -> (cw*EL^2)/sw,
     gc160 -> -((cw^2*EL^2)/sw^2),
     gc161 -> gZp*QBphi*sina,
     gc162 -> cosa*gZp*QBphi,
     gc169 -> -EL,
     gc170 -> -EL,
     gc171 -> -EL,
     gc172 -> (2*EL)/3,
     gc173 -> (2*EL)/3,
     gc174 -> (2*EL)/3,
     gc175 -> -1/3*EL,
     gc176 -> -1/3*EL,
     gc177 -> -1/3*EL,
     gc178 -> GS,
     gc179 -> GS,
     gc180 -> GS,
     gc181 -> GS,
     gc182 -> GS,
     gc183 -> GS,
     gc184 -> (CKM2x1*EL)/(Sqrt[2]*sw),
     gc185 -> (CKM2x2*EL)/(Sqrt[2]*sw),
     gc186 -> (CKM3x3*EL)/(Sqrt[2]*sw),
     gc187 -> (CKM1x1*EL)/(Sqrt[2]*sw),
     gc188 -> (CKM1x2*EL)/(Sqrt[2]*sw),
     gc189 -> (EL*Conjugate[CKM3x3])/(Sqrt[2]*sw),
     gc190 -> (EL*Conjugate[CKM2x1])/(Sqrt[2]*sw),
     gc191 -> (EL*Conjugate[CKM1x1])/(Sqrt[2]*sw),
     gc192 -> (EL*Conjugate[CKM2x2])/(Sqrt[2]*sw),
     gc193 -> (EL*Conjugate[CKM1x2])/(Sqrt[2]*sw),
     gc194 -> EL/(Sqrt[2]*sw),
     gc195 -> EL/(Sqrt[2]*sw),
     gc196 -> EL/(Sqrt[2]*sw),
     gc197 -> EL/(Sqrt[2]*sw),
     gc198 -> EL/(Sqrt[2]*sw),
     gc199 -> EL/(Sqrt[2]*sw),
     gc200L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc200R -> (-2*EL*sw)/(3*cw),
     gc201L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc201R -> (-2*EL*sw)/(3*cw),
     gc202L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc202R -> (-2*EL*sw)/(3*cw),
     gc203L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc203R -> (EL*sw)/(3*cw),
     gc204L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc204R -> (EL*sw)/(3*cw),
     gc205L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc205R -> (EL*sw)/(3*cw),
     gc206 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc207 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc208 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc209L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc209R -> (EL*sw)/cw,
     gc210L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc210R -> (EL*sw)/cw,
     gc211L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc211R -> (EL*sw)/cw,
     gc212 -> gZp*QBq,
     gc213 -> gZp*QBq,
     gc214 -> gZp*QBq,
     gc215 -> gZp*QBq,
     gc216 -> gZp*QBq,
     gc217 -> gZp*QBq,
     gc218L -> gchi,
     gc218R -> -gchi};

